wandb_project: 'DOTS-summer-school'
wandb_entity: 'alexandredelplanque'
seed: 1
device_name: 'cuda'

model: 
  name: 'FasterRCNNResNetFPN'
  from_torchvision: False
  load_from: null
  resume_from: null
  kwargs:
    architecture: 'resnet50'
    num_classes: ${train.datasets.num_classes}
    pretrained_backbone: True
    trainable_backbone_layers: 4
    class_weights: [0.1,1.,2.,1.,6.,12.,1.]
    min_size: 512
    max_size: 512

losses: null

datasets:
  img_size: [512,512]
  anno_type: 'bbox'
  num_classes: 7
  collate_fn: 'collate_fn'
  
  train:
    name: 'CSVDataset'
    csv_file: '/content/data/train/gt_bbox.csv'
    root_dir: '/content/data/train'
    
    sample_on: null

    albu_transforms:
      VerticalFlip:
        p: 0.5
      HorizontalFlip:
        p: 0.5
      RandomRotate90:
        p: 0.5
      RandomBrightnessContrast:
        brightness_limit: 0.2
        contrast_limit: 0.2
        p: 0.2
      Blur:
        blur_limit: 15
        p: 0.2
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    
    end_transforms: null

  validate:
    name: 'CSVDataset'
    csv_file: '/content/data/val.csv'
    root_dir: '/content/data/val'

    albu_transforms:
      Normalize:
        mean: [0.485, 0.456, 0.406]
        std: [0.229, 0.224, 0.225]
    
    end_transforms: null

training_settings:
  trainer: 'FasterRCNNTrainer'
  print_freq: 100
  batch_size: 4
  optimizer: 'adam'
  lr: 1e-3
  weight_decay: 0.001
  auto_lr:
    mode: 'max'
    patience: 10
    threshold: 1e-5
    threshold_mode: 'rel'
    cooldown: 10
    min_lr: 1e-6
    verbose: True
  warmup_iters: 100
  vizual_fn: null
  epochs: 50
  evaluator: 
    name: 'FasterRCNNEvaluator'
    threshold: 0.3
    select_mode: 'max'
    validate_on: 'mAP'
    kwargs:
      print_freq: 10 
  stitcher:
    name: 'FasterRCNNStitcher'
    kwargs:
      overlap: 160
      nms_threshold: 0.5